import os
PROJECT_ROOT = os.path.dirname(os.path.realpath(__file__))
#sys.path.insert(0, PROJECT_ROOT) # no import from local dir

from sqlalchemy import create_engine, asc
from sqlalchemy.orm import sessionmaker
from dbSetup import Cases,Base,Admins
import random, string, httplib2, json, requests

engine = create_engine('sqlite:///{}'.format(os.path.join(PROJECT_ROOT, 'database.db')))
Base.metadata.bind = engine
DBSession = sessionmaker(bind=engine)
session = DBSession()

newAdmin = Admins(username = "baha19", password = "13629354", totalviews=0)
session.add(newAdmin)
session.commit()
print ("Added new admin!")


newCase = Cases(state = "Tunis", totalcases = 1,newcases = 0 , totaldeath= 1, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")

newCase = Cases(state = "Ariana", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")

newCase = Cases(state = "Béja", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Ben Arous", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Bizerte", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Gabés", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Gafsa", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Jendouba", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Kairouan", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Kasserine", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Kébili", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Le kef", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Mahdia", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "La manouba", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Monastir", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Médenine", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Nabeul", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Sfax", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Sidi Bouzid", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Siliana", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Sousse", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Tataouine", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Tozeur", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")
newCase = Cases(state = "Zaghouan", totalcases = 0,newcases = 0 , totaldeath= 0, newdeath = 0 , totalrecovered =0 , serious = 0)
session.add(newCase)
session.commit()
print ("Added case!")







